# Site settings
title: "TextLog"
description: "Not over yet"
baseurl: "/textlog" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Shilong"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
